version: 2.1
orbs:
  docker: circleci/docker@0.5.13

jobs:
  test:
    docker:
      - image: circleci/node:latest 
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: 
          key: dependency-cache-{{ checksum "server/package-lock.json" }}
      - run:
          name: Install npm dependencies
          command: cd server && npm install
      - save_cache: 
          key: dependency-cache-{{ checksum "server/package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run unit tests
          command: 'cd server && npm run test'

workflows:
  test-build-and-publish-docker-image:
    jobs:
      # - test:
      #     filters:
      #       tags:
      #         only: /.*/
      - docker/publish:
          # requires:
          #   - test
          before_build:
            - run:
                name: set image tag
                command: |
                  if [[ -v CIRCLE_TAG ]]; then
                    echo 'export IMAGE_TAG=$(echo $CIRCLE_TAG | tr -d v)' >> $BASH_ENV
                  else
                    echo 'export IMAGE_TAG=$CIRCLE_BRANCH' >> $BASH_ENV
                  fi
          lint-dockerfile: true
          path: server
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: $IMAGE_TAG
          registry: $DOCKER_REGISTRY
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
          # extra_build_args: "--build-arg GITHUB_PACKAGES_TOKEN=$GITHUB_PACKAGES_TOKEN"
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(\-snapshot)?(\-hotfix(\.[0-9]+))?/
            branches:
              ignore:
                - master